name: Diario_News

on:
  schedule:
    # Ejecutar diariamente a las 6:00 AM UTC (2:00 AM Chile)
    - cron: '0 6 * * *'
  
  # Permitir ejecución manual
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'

jobs:
  update-iso-news:
    name: 📊 Actualizar datos ISO Chile
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - name: 📥 Descargar JSON de noticias desde otro repo
      run: |
        curl -L "https://raw.githubusercontent.com/thenext90/noticias_isotools_cms/refs/heads/main/isotools-daily-news.json" -o src/data/isotools-daily-news.json
    - name: 📝 Commit y push si hay cambios
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add src/data/isotools-daily-news.json || true
        git commit -m 'chore: auto-update ISOTools daily news JSON' || echo 'No changes to commit'
        git push || echo 'No changes to push'
